### ISSUE TITLE
OpenApi spec does not include jwt_auth as a security option

### ISSUE THREAD

**Issue by davidnewcomb** [cliffano/swaggy-jenkins#67]
In https://github.com/cliffano/swaggy-jenkins/blob/main/specification/jenkins.yml you have defined: components->securitySchemes `jenkins_auth` and `jwt_auth` but only `jenkins_auth` is used in the security sections.

Shouldn't the following change:
```
  /blue/rest/users/{user}/favorites:
    get:
      ...
      security:
        - jenkins_auth: []
      tags:
        - blueOcean
```
to
```
  /blue/rest/users/{user}/favorites:
    get:
      ...
      security:
        - jenkins_auth: []
        - jwt_auth: []
      tags:
        - blueOcean
```
2 allow both security schema? Otherwise I have to download the yaml file, change it myself and regenerate the stubs. Is this what you mean for us to do?
